/*
 * Copyright (c) 2025 Nordic Semiconductor ASA.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include <uicr/uicr.h>

#define PPIB130 (0x5f925000UL)
#define PPIB133 (0x5f99d000UL)

#define UICR_PERIPHCONF_PREFIX uicr_periphconf_table

UICR_IPCMAP_CHANNEL_CFG(0, NRF_DOMAIN_RADIOCORE, 2, NRF_DOMAIN_GLOBALSLOW, 2);
UICR_IPCMAP_CHANNEL_CFG(1, NRF_DOMAIN_GLOBALSLOW, 0, NRF_DOMAIN_RADIOCORE, 0);
UICR_IPCMAP_CHANNEL_CFG(2, NRF_DOMAIN_GLOBALSLOW, 2, NRF_DOMAIN_RADIOCORE, 2);

/* (DPPIC130 ch.0) <== (DPPIC132 ch.0) */
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(PPIB130, 8);
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(PPIB133, 0);

/* (DPPIC130 ch.2) <== (DPPIC132 ch.2) */
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(PPIB130, 10);
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(PPIB133, 2);

/* (DPPIC130 ch.3) ==> (DPPIC132 ch.3) */
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(PPIB130, 11);
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(PPIB133, 3);
